---
title: "Število prometnih nesreč v Sloveniji v času"
author: "Roman Luštrik (roman.lustrik@biolitika.si)"
date: "`r Sys.Date()`"
output: html_document
---
```{r setup}
library(ggplot2)
```

```{r}
load("./data/raw_accident_data_1995_2021.RData")

pn2004$datum <- as.Date(pn2004$datum, format = "%d.%m.%Y")
pn2021$DatumPN <- as.Date(pn2021$DatumPN, format = "%d.%m.%Y")

pn2021[!duplicated(pn2021$ZaporednaStevilkaPN), ]
```

Calculate number of accidents per day.
```{r}
nad2004 <- aggregate(stevila_zadeve ~ datum, data = pn2004, FUN = length)
colnames(nad2004) <- c("datum", "num_accidents")

nad2021 <- aggregate(ZaporednaStevilkaPN ~ DatumPN, data = pn2021, FUN = function(x) length(unique(x)))
colnames(nad2021) <- c("datum", "num_accidents")

nad <- rbind(nad2004, nad2021)
nad$year <- format(nad$datum, format = "%Y")

yearly.avg <- aggregate(num_accidents ~ year, data = nad, FUN = mean)
```

```{r}
ggplot(nad, aes(x = datum, y = num_accidents)) +
  theme_bw() +
  geom_col() +
  geom_hline(data = yearly.avg, aes(yintercept = num_accidents), color = "grey20") +
  facet_wrap(~ year, scales = "free_x", ncol = 1, strip.position = "right")
ggsave("./figures/figure-2-num-accidents-in-time.pdf", width = 8, height = 24)
```

```{r}
save(nad, file = "./data/num_acc_year.RData")
```

